# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/jupyter-web-app-template',
                'doc_host': 'https://nicole-brewer.github.io',
                'git_url': 'https://github.com/nicole-brewer/jupyter-web-app-template',
                'lib_path': 'jupyter_web_app_template'},
  'syms': {'jupyter_web_app_template.core': {'jupyter_web_app_template.core.foo': ('core.html#foo', 'jupyter_web_app_template/core.py')}}}
