# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/main.ipynb.

# %% auto 0
__all__ = ['Main']

# %% ../nbs/main.ipynb 2
import ipywidgets as widgets
from .data.model import DataModel
from .data.view.select import DataSelectDelegate

# %% ../nbs/main.ipynb 3
class Main(widgets.Tab):
    
    def __init__(self):
        super().__init__()
        self.model = DataModel('../data/land-ocean-temp-index.csv')
        self.data_select_delegate = DataSelectDelegate(self.model)
        self.children = (self.data_select_delegate, widgets.Box(), widgets.Box())
        self.titles = ('Select', 'Smooth Curve', 'Export')
        self.data_select_delegate.next_step_btn.on_click(self._on_next_step_btn_click)
        
    def _on_next_step_btn_click(self, b):
        self.selected_index = 1
