# AUTOGENERATED! DO NOT EDIT! File to edit: ../_nbdev.ipynb.

# %% auto 0
__all__ = ['pprint_traits']

# %% ../_nbdev.ipynb 13
import pprint

def pprint_traits(has_traits):
    trait_names = object_has_traits.trait_names()
    trait_names = [name for name in trait_names if not name.startswith('_')]
    exclude = ['comm', 'log', 'keys']
    trait_names = [name for name in trait_names if name not in exclude]
    traits = {key: getattr(object_has_traits, key) for key in trait_names if object_has_traits.trait_has_value(key)}
    pprint.pprint(traits)
