# AUTOGENERATED! DO NOT EDIT! File to edit: ../_layout.ipynb.

# %% auto 0
__all__ = ['selected_data_accordion', 'INTRO_TEXT', 'SOURCES_TEXT', 'intro_text', 'data_source_text', 'curve_parameter_widgets',
           'left_vbox', 'right_vbox', 'main_widget']

# %% ../_layout.ipynb 3
import ipywidgets as widgets
from .widgets import year_range, poly_order, window_size, plot_output, selected_data_output # import year_range, poly_order, window_size, plot_output, selected_data_output

# %% ../_layout.ipynb 11
window_size.style.handle_color = 'orange'

# %% ../_layout.ipynb 14
year_range.style.handle_color = 'orange'

# %% ../_layout.ipynb 15
year_range.style.description_width = 'initial'

# %% ../_layout.ipynb 17
year_range.layout.width = '500px'

# %% ../_layout.ipynb 19
poly_order.layout.width = '140px'

# %% ../_layout.ipynb 22
selected_data_accordion = widgets.Accordion(titles=('Selected Data',))
selected_data_accordion

# %% ../_layout.ipynb 28
selected_data_accordion.children = (selected_data_output, ) # selected_data_accordion.children = (selected_data_output, )

# %% ../_layout.ipynb 32
selected_data_accordion.selected_index = 0 # selected_data_accordion.selected_index

# %% ../_layout.ipynb 35
INTRO_TEXT = '''
<p><b>Curve Smoothing</b>
This tool is for smoothing and selecting land-ocean temperature data for visualization. Start by selecting a date
range, and then select the smoothing algorithm you want to use. Then click through to the next step, where you will change properies
of the curve smoothing algorithm you selected and visualize the data. 
</p>
'''
SOURCES_TEXT = '''
<p>
<b>About Land-Ocean Temperature Data</b>
<a href="https://climate.nasa.gov/vital-signs/global-temperature/"
target="_blank">Global Temperature (NASA)</a>
,
<a href="https://data.giss.nasa.gov/gistemp/"
target="_blank">GISS Surface Temperature Analysis (NASA)</a>
</p><p>
This site is based on data downloaded from the following site on 2020-07-14:
<a href="https://data.giss.nasa.gov/gistemp/graphs/graph_data/Global_Mean_Estimates_based_on_Land_and_Ocean_Data/graph.txt"  # noqa
target="_blank">Global Mean Estimates based on Land and Ocean Data (NASA)</a>
'''

# %% ../_layout.ipynb 37
intro_text = widgets.HTML(value = INTRO_TEXT, layout = widgets.Layout(max_width = '500px'))
data_source_text = widgets.HTML(value = SOURCES_TEXT, layout = widgets.Layout(max_width = '500px'))

# %% ../_layout.ipynb 45
curve_parameter_widgets = widgets.HBox(children = (window_size, poly_order))
curve_parameter_widgets.layout.width = '500px'
curve_parameter_widgets

# %% ../_layout.ipynb 47
left_vbox = widgets.VBox()
left_vbox.children = (intro_text, data_source_text, year_range, curve_parameter_widgets) #(intro_text, data_source_text, year_range, curve_parameter_widgets) # add year_range, selected_data_accordion, curve_parameter_widgets to the VBox
left_vbox

# %% ../_layout.ipynb 51
for child in left_vbox.children: # how might we add padding to each of the widgets
    child.layout.margin = '15px 0 15px 0' #

# %% ../_layout.ipynb 53
right_vbox = widgets.VBox(children = (selected_data_accordion, plot_output)) # add the selected_data_accordion and the plot_output to a VBox widget
right_vbox

# %% ../_layout.ipynb 55
main_widget = widgets.HBox(children = (left_vbox, right_vbox))
main_widget

# %% ../_layout.ipynb 57
right_vbox.layout.margin = '0 0 0 30px'
right_vbox.layout.align_items = 'flex-end'
selected_data_accordion.layout.width = '88%'
left_vbox.layout.min_width = '500px'
